@startuml
skinparam maxmessagesize 20

":TestCase" -> "azul:Jugador" : atacarAPais (argentina,brasil,2)

"azul:Jugador" -> "argentina:Pais" : prepararParaLaBatalla (brasil,2)
"argentina:Pais" -> "azul:Jugador" : tirar(2)
"azul:Jugador" -> "dadosAzul:Dados" : tirar(2)
"dadosAzul:Dados" --> "azul:Jugador" : void

"azul:Jugador" -> "brasil:Pais" : conseguirContrincante()
"brasil:Pais" -> "rojo:Jugador" : tirar(2)
"rojo:Jugador" -> "dadosRojo:Dados" : tirar(2)
"dadosRojo:Dados" --> "rojo:Jugador":
"rojo:Jugador" --> "brasil:Pais":

"brasil:Pais" --> "azul:Jugador" : rojo
"azul:Jugador" -> "azul:Jugador" : entrarEnGuerra (rojo,argentina,brasil)

loop el pais defensor pierde 2 veces
    "azul:Jugador" -> "azul:Jugador" : batallar(rojo, argentina, brasil, numeroDeBatalla)
    "azul:Jugador" -> "dadosAzul:Dados" : comparar (dadosRojo, numeroDeBatalla)
    "dadosAzul:Dados" --> "azul:Jugador" : true
    "azul:Jugador" -> "brasil:Pais" : restarEjercitos(1)
    "brasil:Pais" --> "azul:Jugador":
    end
"azul:Jugador" -> "brasil:Pais" : conquistarPais (azul,argentina)

"brasil:Pais" -> "brasil:Pais" : sumarEjercitos(1)
"brasil:Pais" -> "argentina:Pais" : restarEjercitos(1)
"argentina:Pais" --> "brasil:Pais":
"brasil:Pais" -> "rojo:Jugador" : perderContinente (america)
"rojo:Jugador" --> "brasil:Pais":
"brasil:Pais" -> "rojo:Jugador" : perderPais(brasil)
"brasil:Pais" -> "azul:Jugador" : conquistarContinente(america)
"azul:Jugador" -> "turno:Turno": actualizarEjercitosAColocar()
"turno:Turno" --> "azul:Jugador": void
"azul:Jugador" --> ":TestCase": void

@enduml